title: Harsh Jaiswal
logo: /assets/img/logo.png
description: Passionate data analytics professional eager to secure a full-time role as a Data Analyst or Business Analyst, where I can combine my love for problem-solving and storytelling through data to drive impactful business decisions.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
